<?php

namespace anstiss\simpleTypes;

class dm_tipoTransacao {

    const ENVIO_LOTE_GUIAS = 'ENVIO_LOTE_GUIAS';
    const SOLIC_DEMONSTRATIVO_RETORNO = 'SOLIC_DEMONSTRATIVO_RETORNO';
    const SOLIC_STATUS_PROTOCOLO = 'SOLIC_STATUS_PROTOCOLO';
    const SOLICITACAO_PROCEDIMENTOS = 'SOLICITACAO_PROCEDIMENTOS';
    const PROTOCOLO_RECEBIMENTO = 'PROTOCOLO_RECEBIMENTO';
    const SITUACAO_PROTOCOLO = 'SITUACAO_PROTOCOLO';
    const RESPOSTA_SOLICITACAO = 'RESPOSTA_SOLICITACAO';
    const DEMONSTRATIVO_PAGAMENTO = 'DEMONSTRATIVO_PAGAMENTO';
    const DEMONSTRATIVO_ANALISE_CONTA = 'DEMONSTRATIVO_ANALISE_CONTA';
    const DEMONSTRATIVO_ODONTOLOGIA = 'DEMONSTRATIVO_ODONTOLOGIA';
    const CANCELAMENTO_GUIA_RECIBO = 'CANCELAMENTO_GUIA_RECIBO';
    const CANCELA_GUIA = 'CANCELA_GUIA';
    const VERIFICA_ELEGIBILIDADE = 'VERIFICA_ELEGIBILIDADE';
    const SITUACAO_ELEGIBILIDADE = 'SITUACAO_ELEGIBILIDADE';
    const AUTORIZACAO_ODONTOLOGIA = 'AUTORIZACAO_ODONTOLOGIA';
    const SOLICITA_STATUS_AUTORIZACAO = 'SOLICITA_STATUS_AUTORIZACAO';
    const STATUS_AUTORIZACAO = 'STATUS_AUTORIZACAO';
    const ENVIO_ANEXO = 'ENVIO_ANEXO';
    const PROTOCOLO_RECEBIMENTO_ANEXO = 'PROTOCOLO_RECEBIMENTO_ANEXO';
    const COMUNICACAO_BENEFICIARIO = 'COMUNICACAO_BENEFICIARIO';
    const RECIBO_COMUNICACAO = 'RECIBO_COMUNICACAO';
    const RECURSO_GLOSA = 'RECURSO_GLOSA';
    const RESPOSTA_RECURSO_GLOSA = 'RESPOSTA_RECURSO_GLOSA';

}
